mun_logistics/booking/urls.py
# booking/urls.py
from django.urls import path
from .views import BookingListView, BookingDetailView,BookingCreate,BookingUpdate


urlpatterns = [
    path("booking/<int:pk>/",BookingDetailView.as_view(), name="booking_detail"),
    path("bookingcreate/",BookingCreate.as_view(),name="create_booking"),
    path("booking_update/int:pk", BookingUpdate.as_view(), name="update_booking"),
    path("", BookingListView.as_view(), name="home"),
]

mun_logistics/mun_logistics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("booking.urls")),
]

mun_logistics/booking/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse

# Create your models here.
class Booking_Details(models.Model):
    sender_name = models.CharField(max_length=400)
    sender_address = models.CharField(max_length=400)
    sender_phone = PhoneNumberField()
    sender_email = models.EmailField(max_length = 254)
    collection_date = models.DateField()
    #ItemesColllected
    time_slot = models.TimeField()
    boxes = models.IntegerField()
    drums = models.IntegerField()
    odd_parcels_items = models.CharField(max_length=400)
    #insert_image = models.ImageField #Todo
    #Receivers Information
    receiver_name = models.CharField(max_length=400)
    receiver_address = models.CharField(max_length=400)
    receiver_phone = PhoneNumberField()
    receiver_email = models.EmailField(max_length = 254)

    def __str__(self):
        return self.sender_name
    def get_absolute_url(self):
        return reverse("booking_detail", kwargs={"pk": self.pk})

class ShippingDetails(models.Model):
    origin = models.CharField(max_length=400)
    destination = models.CharField(max_length=400)
    shipment_mode = models.CharField(max_length=400)
    shipment_date = models.DateField()
    time_updated = models.TimeField()
    location = models.CharField(max_length=400)
    updated_by = models.CharField(max_length=400)
    remarks = models.CharField(max_length=400)

mun_logistics/booking/views.py
# booking/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from .models import Booking_Details
from django.urls import reverse_lazy
class BookingListView(ListView):
    model = Booking_Details
    template_name = "home.html"
    
class BookingDetailView(DetailView):
    model = Booking_Details   
    template_name = "booking_detail.html"

class BookingCreate(CreateView):
    model = Booking_Details
    fields = "__all__"
    template_name = "create_booking.html"
    success_url = reverse_lazy("home")

class BookingUpdate(UpdateView):
    model = Booking_Details
    fields = "__all__"
    template_name = "update_booking.html"
    #success_url = reverse_lazy("home")

mun_logistics/templates/base.html
<!-- templates/base.html -->
{% load static %}
<html>
    <head>
        <title>Booking Form</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
            rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">   
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
        <header>
            <h1><a href="{% url 'home' %}">Booking Summary</a></h1>
        </header>
        <div>
            {% block content %}
            
            {% endblock content %}
        </div>
    </body>
</html>

mun_logistics/templates/booking_detail.html
{% extends "base.html" %}
{% block content %}

            <div class="card" style="width: 18rem;">
                <div class="card-header">
                <h3>Collection Details</h3>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Sender: {{ booking_details.sender_name }}</li>
                <li class="list-group-item">Address: {{ booking_details.sender_address }}</li>
                <li class="list-group-item">Phone: {{ booking_details.sender_phone }}</li>
                <li class="list-group-item">Email: {{ booking_details.sender_email }}</li>
                <li class="list-group-item">Collection Date: {{ booking_details.collection_date}}</li>
                <li class="list-group-item">Time Slot: {{ booking_details.time_slot }}</li>
              </ul>
            </div>
        
            <br>

        <div class="card" style="width: 18rem;">
        <div class="card-header">
            <h3>Items To Be Colleccted</h3>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Boxes: {{ booking_details.boxes }}</li>
        <li class="list-group-item">Drums: {{ booking_details.drums }}</li>
        <li class="list-group-item">Odd Parcels/Items: {{ booking_details.odd_parcels_items }}</li>
      </ul>
    </div>
    <br>

        <div class="card" style="width: 18rem;">
        <div class="card-header">
            <h3>Recepient Details</h3>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">Recipient: {{ booking_details.receiver_name }}</li>
        <li class="list-group-item">Address: {{ booking_details.receiver_address }}</li>
        <li class="list-group-item">Phone: {{ booking_details.receiver_phone }}</li>
        <li class="list-group-item">Email: {{ booking_details.receiver_email }}</li>
      </ul>
    </div>
    <br>
</div>
    <a href="#" class="btn btn-primary">Edit Boooking</a>
{% endblock content %}

mun_logistics/templates/create_booking.html
{% extends "base.html" %}
{% block content %}

<h1>Create a Booking</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock content %}

mun_logistics/templates/home.html
<!-- templates/home.html -->
{% extends "base.html" %}
{% block content %}
<a href="{% url 'create_booking' %}" class="btn btn-primary">Create a Boooking</a>

<br>


{% for booking_details in booking_details_list %}
    <!-- <div class="post-entry">
        <h2><a href="{% url 'booking_detail' booking_details.pk %}">{{ booking_details.sender_name }}</a></h2>
        <p>{{ booking_details.sender_address }}</p>
        
    </div> -->
    <div class="card">
        <div class="card-header">
            {{ booking_details.sender_name }}
        </div>
        <div class="card-body">
          <h5 class="card-title">{{ booking_details.receiver_name}}</h5>
          <p class="card-text">{{ booking_details.sender_address }}</p>
          <a href="{% url 'booking_detail' booking_details.pk %}" class="btn btn-primary">View Booking</a>
          <a href="{% url 'booking_detail' booking_details.pk %}" class="btn btn-primary">Edit Booking</a>
        </div>
      </div>
{% endfor %}
{% endblock content %}

mun_logistics/templates/update_booking.html
{% extends "base.html" %}
{% block content %}

<h1>Update Booking</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock content %}